<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg</groupId>
      <artifactId>scheduler</artifactId>
      <version>0.7.7</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.scheduler</groupId>
   <artifactId>scheduler-domain</artifactId>
   <packaging>jar</packaging>

   <name>Scheduler domain</name>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <!-- ============================================== -->
      <!-- ================ FRAMEWORK =================== -->
      <!-- ============================================== -->
      <dependency>
         <!-- Event -->
         <groupId>com.bernardomg.framework</groupId>
         <artifactId>event</artifactId>
         <version>${bernardomg.framework.event.version}</version>
      </dependency>
      <!-- ============================================== -->
      <!-- ================== SPRING ==================== -->
      <!-- ============================================== -->
      <dependency>
         <!-- Spring Boot: Autoconfigure -->
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-autoconfigure</artifactId>
      </dependency>
   </dependencies>

</project>
