<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

	<!-- ********************************************** -->
	<!-- ****************** BASE POM ****************** -->
	<!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.association.calendar</groupId>
      <artifactId>association-calendar</artifactId>
      <version>1.0.0-SNAPSHOT</version>
   </parent>

	<!-- ********************************************** -->
	<!-- **************** PROJECT INFO **************** -->
	<!-- ********************************************** -->

   <groupId>com.bernardomg.association.calendar</groupId>
   <artifactId>association-scheduled-game-rest-adapter</artifactId>
   <packaging>jar</packaging>

   <name>Association Scheduled Game REST Adapter</name>

	<!-- ********************************************** -->
	<!-- **************** PROPERTIES ****************** -->
	<!-- ********************************************** -->

   <properties>
     <openapi.generator.maven.plugin.inputSpec>${project.basedir}/src/main/resources/openapi/game.yml</openapi.generator.maven.plugin.inputSpec>
     <openapi.generator.maven.plugin.apiPackage>com.bernardomg.association.calendar.game.adapter.outbound.rest.controller</openapi.generator.maven.plugin.apiPackage>
     <openapi.generator.maven.plugin.modelPackage>com.bernardomg.association.calendar.game.adapter.outbound.rest.dto</openapi.generator.maven.plugin.modelPackage>
   </properties>

	<!-- ********************************************** -->
	<!-- *************** DEPENDENCIES ***************** -->
	<!-- ********************************************** -->

   <dependencies>
	  <!-- ============================================== -->
	  <!-- ================ FRAMEWORK =================== -->
	  <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-domain</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-usecase</artifactId>
      </dependency>
      <dependency>
			<!-- Spring WS Security Starter -->
         <groupId>com.bernardomg.framework.spring</groupId>
         <artifactId>spring-ws-security-starter</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================= JAKARTA ==================== -->
      <!-- ============================================== -->
      <dependency>
          <!-- Jakarta Servlet API -->
         <groupId>jakarta.servlet</groupId>
         <artifactId>jakarta.servlet-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <!-- Jakarta validation -->
         <groupId>jakarta.validation</groupId>
         <artifactId>jakarta.validation-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <!-- ============================================== -->
      <!-- ======= TEST ENVIRONMENT DEPENDENCIES ======== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-testing</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.hibernate.validator</groupId>
         <artifactId>hibernate-validator</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.fasterxml.jackson.datatype</groupId>
         <artifactId>jackson-datatype-jsr310</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>org.hibernate.validator</groupId>
         <artifactId>hibernate-validator</artifactId>
         <scope>test</scope>
      </dependency>
   </dependencies>

	<!-- ********************************************** -->
	<!-- ******************* BUILD ******************** -->
	<!-- ********************************************** -->

   <build>
      <plugins>
          <plugin>
             <groupId>org.openapitools</groupId>
             <artifactId>openapi-generator-maven-plugin</artifactId>
             <executions>
                <execution>
                   <goals>
                      <goal>generate</goal>
                   </goals>
                </execution>
             </executions>
          </plugin>
      </plugins>
   </build>

</project>
