<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg</groupId>
      <artifactId>common</artifactId>
      <version>0.7.14</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.asset</groupId>
   <artifactId>asset</artifactId>
   <packaging>pom</packaging>

   <name>Assets</name>

   <!-- ********************************************** -->
   <!-- ******************* MODULES ****************** -->
   <!-- ********************************************** -->

   <modules>
      <module>domain</module>
      <module>testing</module>
      <module>usecase</module>
      <module>rest-adapter</module>
      <module>s3-adapter</module>
      <module>spring-jpa-model</module>
      <module>spring-starter</module>
   </modules>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencyManagement>
      <dependencies>
         <!-- ============================================== -->
         <!-- ================= PROJECT ==================== -->
         <!-- ============================================== -->
         <dependency>
            <groupId>com.bernardomg.asset</groupId>
            <artifactId>asset-testing</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>com.bernardomg.asset</groupId>
            <artifactId>asset-domain</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>com.bernardomg.asset</groupId>
            <artifactId>asset-rest-adapter</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>com.bernardomg.asset</groupId>
            <artifactId>asset-s3-adapter</artifactId>
            <version>${project.version}</version>
         </dependency>
         <dependency>
            <groupId>com.bernardomg.asset</groupId>
            <artifactId>asset-spring-starter</artifactId>
            <version>${project.version}</version>
         </dependency>
      </dependencies>
   </dependencyManagement>

</project>
