openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /security/user/{username}/profile:
    $ref: paths/user_profile.yml
  /security/user/{username}/profile/{memberNumber}:
    $ref: paths/user_profile_by_id.yml
  /profile/{number}/sponsor:
    $ref: paths/profile_sponsorship.yml
  /profile/{number}/guest:
    $ref: paths/profile_guest.yml
  /profile/sponsor:
    $ref: paths/sponsors.yml
  /profile/sponsor/{number}:
    $ref: paths/sponsors_by_id.yml
  /profile/guest:
    $ref: paths/guests.yml
  /profile/guest/{number}:
    $ref: paths/guests_by_id.yml
  /library/author:
    $ref: paths/authors.yml
  /library/author/{number}:
    $ref: paths/authors_by_id.yml
  /library/bookType:
    $ref: paths/book_types.yml
  /library/bookType/{number}:
    $ref: paths/book_types_by_id.yml
  /library/gameSystem:
    $ref: paths/game_systems.yml
  /library/gameSystem/{number}:
    $ref: paths/game_systems_by_id.yml
  /library/publisher:
    $ref: paths/publishers.yml
  /library/publisher/{number}:
    $ref: paths/publishers_by_id.yml
  /library/lending:
    $ref: paths/book_lendings.yml
  /library/book/fiction:
    $ref: paths/books_fiction.yml
  /library/book/fiction/{number}:
    $ref: paths/books_fiction_by_id.yml
  /library/book/game:
    $ref: paths/books_game.yml
  /library/book/game/{number}:
    $ref: paths/books_game_by_id.yml
  /library/book:
    $ref: paths/books_report.yml