<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

	<!-- ********************************************** -->
	<!-- ****************** BASE POM ****************** -->
	<!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.association.calendar</groupId>
      <artifactId>association-calendar</artifactId>
      <version>1.0.0-SNAPSHOT</version>
   </parent>

	<!-- ********************************************** -->
	<!-- **************** PROJECT INFO **************** -->
	<!-- ********************************************** -->

   <groupId>com.bernardomg.association.calendar</groupId>
   <artifactId>association-calendar-spring-starter</artifactId>
   <packaging>jar</packaging>

   <name>Association Calendar Spring Starter</name>

	<!-- ********************************************** -->
	<!-- *************** DEPENDENCIES ***************** -->
	<!-- ********************************************** -->

   <dependencies>
	  <!-- ============================================== -->
	  <!-- ================ FRAMEWORK =================== -->
	  <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-domain</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-usecase</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-spring-jpa-adapter</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-activity-rest-adapter</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-scheduled-game-rest-adapter</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.calendar</groupId>
         <artifactId>association-calendar-type-rest-adapter</artifactId>
      </dependency>
      <dependency>
			<!-- Spring WS Security Starter -->
         <groupId>com.bernardomg.framework.spring</groupId>
         <artifactId>spring-ws-security-starter</artifactId>
      </dependency>
	  <!-- ============================================== -->
	  <!-- ================== SPRING ==================== -->
	  <!-- ============================================== -->
      <dependency>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-autoconfigure</artifactId>
      </dependency>
   </dependencies>

</project>
