openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /files:
    $ref: paths/files.yml
  /files/{number}:
    $ref: paths/files_by_id.yml
  /files/{number}/content:
    $ref: paths/files_content.yml
