<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.association.profile</groupId>
      <artifactId>association-profile</artifactId>
      <version>1.0.0-SNAPSHOT</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.association.profile</groupId>
   <artifactId>association-profile-rest-adapter</artifactId>
   <packaging>jar</packaging>

   <name>Association Profiles REST Adapter</name>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <dependency>
         <groupId>com.bernardomg.association.profile</groupId>
         <artifactId>association-profile-domain</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.profile</groupId>
         <artifactId>association-profile-usecase</artifactId>
      </dependency>
      <dependency>
         <!-- Spring WS Security Starter -->
         <groupId>com.bernardomg.framework.spring</groupId>
         <artifactId>spring-ws-security-starter</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================= JAKARTA ==================== -->
      <!-- ============================================== -->
      <dependency>
          <!-- Jakarta Servlet API -->
         <groupId>jakarta.servlet</groupId>
         <artifactId>jakarta.servlet-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <!-- Jakarta validation -->
         <groupId>jakarta.validation</groupId>
         <artifactId>jakarta.validation-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <!-- ============================================== -->
      <!-- ======= TEST ENVIRONMENT DEPENDENCIES ======== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg</groupId>
         <artifactId>testing</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.profile</groupId>
         <artifactId>association-profile-testing</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
	     <groupId>org.hibernate.validator</groupId>
	     <artifactId>hibernate-validator</artifactId>
	     <scope>test</scope>
	  </dependency>
      <dependency>
         <groupId>com.fasterxml.jackson.datatype</groupId>
         <artifactId>jackson-datatype-jsr310</artifactId>
         <scope>test</scope>
      </dependency>
   </dependencies>

   <!-- ********************************************** -->
   <!-- ******************* BUILD ******************** -->
   <!-- ********************************************** -->

   <build>
      <plugins>
          <plugin>
             <groupId>org.openapitools</groupId>
             <artifactId>openapi-generator-maven-plugin</artifactId>
             <executions>
                <execution>
                   <id>profile</id>
                   <goals>
                      <goal>generate</goal>
                   </goals>
                   <configuration>
                      <inputSpec>${project.basedir}/src/main/resources/openapi/profile/profile.yml</inputSpec>
                      <apiPackage>com.bernardomg.association.profile.adapter.outbound.rest.controller</apiPackage>
                      <modelPackage>com.bernardomg.association.profile.adapter.outbound.rest.dto</modelPackage>
                   </configuration>
                </execution>
                <execution>
                   <id>guest</id>
                   <goals>
                      <goal>generate</goal>
                   </goals>
                   <configuration>
                      <inputSpec>${project.basedir}/src/main/resources/openapi/guest/guest.yml</inputSpec>
                      <apiPackage>com.bernardomg.association.guest.adapter.outbound.rest.controller</apiPackage>
                      <modelPackage>com.bernardomg.association.guest.adapter.outbound.rest.dto</modelPackage>
                   </configuration>
                </execution>
                <execution>
                   <id>member</id>
                   <goals>
                      <goal>generate</goal>
                   </goals>
                   <configuration>
                      <inputSpec>${project.basedir}/src/main/resources/openapi/member/member.yml</inputSpec>
                      <apiPackage>com.bernardomg.association.member.adapter.outbound.rest.controller</apiPackage>
                      <modelPackage>com.bernardomg.association.member.adapter.outbound.rest.dto</modelPackage>
                   </configuration>
                </execution>
                <execution>
                   <id>sponsor</id>
                   <goals>
                      <goal>generate</goal>
                   </goals>
                   <configuration>
                      <inputSpec>${project.basedir}/src/main/resources/openapi/sponsor/sponsor.yml</inputSpec>
                      <apiPackage>com.bernardomg.association.sponsor.adapter.outbound.rest.controller</apiPackage>
                      <modelPackage>com.bernardomg.association.sponsor.adapter.outbound.rest.dto</modelPackage>
                   </configuration>
                </execution>
             </executions>
          </plugin>
      </plugins>
   </build>

</project>
