openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /security/user/{username}/profile:
    $ref: paths/user_profile.yml
  /security/user/{username}/profile/{memberNumber}:
    $ref: paths/user_profile_by_id.yml