<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.asset</groupId>
      <artifactId>asset</artifactId>
      <version>0.7.13</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.asset</groupId>
   <artifactId>asset-usecase</artifactId>
   <packaging>jar</packaging>

   <name>Assets Usecase</name>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <dependency>
         <groupId>com.bernardomg.asset</groupId>
         <artifactId>asset-domain</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.asset</groupId>
         <artifactId>asset-testing</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.framework</groupId>
         <artifactId>pagination</artifactId>
      </dependency>
      <dependency>
         <groupId>jakarta.transaction</groupId>
         <artifactId>jakarta.transaction-api</artifactId>
      </dependency>
   </dependencies>

</project>
