openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /settings:
    $ref: paths/settings.yml
  /settings/{code}:
    $ref: paths/settings_by_id.yml
  /settings/public:
    $ref: paths/settings_public.yml