openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /member:
    $ref: paths/public_members.yml
  /member/count:
    $ref: paths/public_members_count.yml
  /member/{number}:
    $ref: paths/public_members_by_id.yml
  /member/evolution:
    $ref: paths/membership_monthly_evolution.yml
  /profile/member:
    $ref: paths/member_profiles.yml
  /profile/member/{number}:
    $ref: paths/member_profiles_by_id.yml
  /profile/{number}/member:
    $ref: paths/profile_membership.yml