<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

   <modelVersion>4.0.0</modelVersion>

   <!-- ********************************************** -->
   <!-- ****************** BASE POM ****************** -->
   <!-- ********************************************** -->

   <parent>
      <groupId>com.bernardomg.association.transaction</groupId>
      <artifactId>association-transaction</artifactId>
      <version>1.0.0-SNAPSHOT</version>
   </parent>

   <!-- ********************************************** -->
   <!-- **************** PROJECT INFO **************** -->
   <!-- ********************************************** -->

   <groupId>com.bernardomg.association.transaction</groupId>
   <artifactId>association-transaction-rest-adapter</artifactId>
   <packaging>jar</packaging>

   <name>Association Transactions REST Adapter</name>

   <!-- ********************************************** -->
   <!-- **************** PROPERTIES ****************** -->
   <!-- ********************************************** -->

   <properties>
     <openapi.generator.maven.plugin.inputSpec>${project.basedir}/src/main/resources/openapi/transaction.yml</openapi.generator.maven.plugin.inputSpec>
     <openapi.generator.maven.plugin.apiPackage>com.bernardomg.association.transaction.adapter.outbound.rest.controller</openapi.generator.maven.plugin.apiPackage>
     <openapi.generator.maven.plugin.modelPackage>com.bernardomg.association.transaction.adapter.outbound.rest.dto</openapi.generator.maven.plugin.modelPackage>
   </properties>

   <!-- ********************************************** -->
   <!-- *************** DEPENDENCIES ***************** -->
   <!-- ********************************************** -->

   <dependencies>
      <dependency>
         <groupId>com.bernardomg.association.transaction</groupId>
         <artifactId>association-transaction-domain</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.transaction</groupId>
         <artifactId>association-transaction-usecase</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================== OPENAPI =================== -->
      <!-- ============================================== -->
      <dependency>
        <groupId>org.openapitools</groupId>
        <artifactId>jackson-databind-nullable</artifactId>
      </dependency>
      <dependency>
        <groupId>io.swagger.core.v3</groupId>
        <artifactId>swagger-annotations</artifactId>
      </dependency>
	  <!-- ============================================== -->
	  <!-- ================ FRAMEWORK =================== -->
	  <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>access-decorator</artifactId>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.framework.security</groupId>
         <artifactId>security-model</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ================= JAKARTA ==================== -->
      <!-- ============================================== -->
      <dependency>
          <!-- Jakarta Servlet API -->
         <groupId>jakarta.servlet</groupId>
         <artifactId>jakarta.servlet-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <!-- Jakarta validation -->
         <groupId>jakarta.validation</groupId>
         <artifactId>jakarta.validation-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <dependency>
         <!-- Jakarta annotation API -->
         <groupId>jakarta.annotation</groupId>
         <artifactId>jakarta.annotation-api</artifactId>
         <scope>provided</scope>
      </dependency>
      <!-- ============================================== -->
      <!-- ================== SPRING ==================== -->
      <!-- ============================================== -->
      <dependency>
         <!-- Spring Web MVC -->
         <groupId>org.springframework</groupId>
         <artifactId>spring-web</artifactId>
      </dependency>
      <dependency>
         <!-- Spring Context -->
         <groupId>org.springframework</groupId>
         <artifactId>spring-context</artifactId>
      </dependency>
      <!-- ============================================== -->
      <!-- ======= TEST ENVIRONMENT DEPENDENCIES ======== -->
      <!-- ============================================== -->
      <dependency>
         <groupId>com.bernardomg</groupId>
         <artifactId>testing</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.bernardomg.association.transaction</groupId>
         <artifactId>association-transaction-testing</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
         <groupId>com.fasterxml.jackson.datatype</groupId>
         <artifactId>jackson-datatype-jsr310</artifactId>
         <scope>test</scope>
      </dependency>
      <dependency>
	     <groupId>org.hibernate.validator</groupId>
	     <artifactId>hibernate-validator</artifactId>
	     <scope>test</scope>
	  </dependency>
   </dependencies>

   <!-- ********************************************** -->
   <!-- ******************* BUILD ******************** -->
   <!-- ********************************************** -->

   <build>
      <plugins>
          <plugin>
             <groupId>org.openapitools</groupId>
             <artifactId>openapi-generator-maven-plugin</artifactId>
             <executions>
                <execution>
                   <goals>
                      <goal>generate</goal>
                   </goals>
                </execution>
             </executions>
          </plugin>
      </plugins>
   </build>

</project>
