openapi: 3.0.3
info:
  title: Ucronia API
  version: 1.0.0
  description: API for managing the Ucronia association.
servers:
  - url: https://localhost
    description: Local development
paths:
  /member:
    $ref: paths/members.yml
  /member/summary:
    $ref: paths/members_summary.yml
  /member/{number}:
    $ref: paths/members_by_id.yml
  /member/evolution:
    $ref: paths/membership_monthly_evolution.yml
  /profile/member:
    $ref: paths/member_profiles.yml
  /profile/member/{number}:
    $ref: paths/member_profiles_by_id.yml
  /profile/{number}/member:
    $ref: paths/profile_membership.yml
  /fee:
    $ref: paths/fees.yml
  /fee/type:
    $ref: paths/fee_types.yml
  /fee/type/{number}:
    $ref: paths/fee_types_by_id.yml
  /fee/{month}/{member}:
    $ref: paths/fees_by_id.yml
  /fee/pay:
    $ref: paths/fees_pay.yml
  /fee/range:
    $ref: paths/fees_calendar_range.yml
  /fee/{year}:
    $ref: paths/fees_calendar.yml
  /fee/summary:
    $ref: paths/fees_summary.yml
  /user/fee:
    $ref: paths/user_fees.yml